apply plugin: 'com.android.application'
apply plugin: 'com.google.protobuf'
android {
    compileSdkVersion 28
    defaultConfig {
        applicationId "com.ubtrobot.mini.sdkdemo"
        minSdkVersion 24
        targetSdkVersion 28
        versionCode 1
        versionName "1.0"
        testInstrumentationRunner "android.support.test.runner.AndroidJUnitRunner"
        buildConfigField "String", "API_SPRING_PATH", "\"${getLocalProperty('api.spring.path', '')}\""
        buildConfigField "String", "API_PYTHON_PATH", "\"${getLocalProperty('api.python.path', '')}\""
        buildConfigField "String", "API_WEBSOCKET", "\"${getLocalProperty('api.websocket', '')}\""
        buildConfigField "String", "API_LOGSERVICE_PATH", "\"${getLocalProperty('api.logservice.path', '')}\""

        multiDexEnabled true
        ndk {
            abiFilters 'arm64-v8a'
        }
    }

    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'
        }
    }

    packagingOptions {
        pickFirst 'lib/arm64-v8a/libtvad.so'
        pickFirst 'lib/armeabi-v7a/libtvad.so'
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8
    }

    lintOptions {
        abortOnError false
    }
}

repositories {
    google()
    mavenCentral()
    maven { url "https://jitpack.io" }
    maven { url "https://maven.webrtc.org" }   // thêm repo chính thức WebRTC
    flatDir {
        dirs 'libs'
    }
    sourceSets {
        main {
            proto {
                srcDir 'src/main/proto'
            }
            java {
                srcDirs 'src/main/java', 'build/generated/source/proto/main/java'
            }
        }
    }
}

dependencies {
    implementation fileTree(include: ['*.jar'], dir: 'libs')
    implementation 'com.android.support:appcompat-v7:28.+'
    implementation 'com.android.support.constraint:constraint-layout:1.0.2'
    implementation files('libs/speech-sdk.jar')
    implementation files('libs/mini-outer-sdk-2.4.2.jar')
    implementation files('libs/Msc.jar')
    testImplementation 'junit:junit:4.12'
    androidTestImplementation 'com.android.support.test:runner:1.0.1'
    androidTestImplementation 'com.android.support.test.espresso:espresso-core:3.0.1'
    implementation(name: 'phonecall-sdk-release', ext: 'aar')
    implementation(name: 'utillib-1.2.8', ext: 'aar')
    implementation 'com.google.code.gson:gson:2.7'
    implementation 'com.journeyapps:zxing-android-embedded:4.3.0'
    implementation 'com.google.zxing:core:3.3.0'
    implementation 'com.squareup.okhttp3:okhttp:4.12.0'
    implementation 'com.android.support:multidex:1.0.3'
    implementation 'com.google.zxing:core:3.5.0'
    implementation "org.java-websocket:Java-WebSocket:1.5.2"
    implementation "com.squareup.retrofit2:retrofit:2.9.0"
    implementation "com.squareup.retrofit2:converter-gson:2.9.0"
    implementation 'com.squareup.okhttp3:logging-interceptor:4.12.0'
    compileOnly 'org.projectlombok:lombok:1.18.34'
    annotationProcessor 'org.projectlombok:lombok:1.18.34'

    //Speech
    implementation(name: 'impl-wakeup-dingdang-1.0.0', ext: 'aar')
    implementation(name: 'sal-speech-1.0.0', ext: 'aar')
    implementation(name: 'speechFramework-oversea-release', ext: 'aar')
    implementation(name: 'tencent-vad-1.0.0', ext: 'aar')
    implementation(name: 'weinalib-5.0.1', ext: 'aar')
    implementation(name: 'wakeup-5.0.0', ext: 'aar')
    implementation 'com.alphacephei:vosk-android:0.3.47'

    // WebRTC
    implementation 'com.infobip:google-webrtc:1.0.0035529'

    implementation 'com.google.mlkit:translate:17.0.3'
}

protobuf {
    protoc {
        artifact = 'com.google.protobuf:protoc:3.4.0'
    }
    generateProtoTasks {
        all().each { task ->
            task.builtins {
                java { }
            }
        }
    }
}